# Generated by Django 5.2.3 on 2025-07-21 16:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0002_rename_name_board_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='task',
            name='asisignees',
        ),
        migrations.AddField(
            model_name='task',
            name='asisignees_id',
            field=models.ManyToManyField(related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='reviewver_id',
            field=models.ManyToManyField(related_name='reviewed_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('H', 'HIGH'), ('M', 'MEDIUM'), ('L', 'LOW')], max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to_do', 'TO_DO'), ('in_progress', 'IN_PROGRESS'), ('in_review', 'In_Review'), ('Finished', 'FINISHED')], max_length=30),
        ),
    ]
