# Generated by Django 5.2.3 on 2025-07-24 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0004_board_owner_alter_board_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='reviewver_id',
            new_name='reviewer_id',
        ),
    ]
