# Generated by Django 5.2.3 on 2025-07-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0005_rename_reviewver_id_task_reviewer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='asisignees_id',
            new_name='assignees',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='reviewer_id',
            new_name='reviewers',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to_do', 'TO_DO'), ('in_progress', 'IN_PROGRESS'), ('in_review', 'IN_REVIEW'), ('finished', 'FINISHED')], max_length=30),
        ),
    ]
