# Generated by Django 5.2.4 on 2025-08-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0011_remove_task_owner_alter_task_board_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to_do', 'TO_DO'), ('progress', 'IN_PROGRESS'), ('review', 'IN_REVIEW'), ('done', 'DONE')], max_length=30),
        ),
    ]
