# Generated by Django 5.2.4 on 2025-08-10 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='bio',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='location',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='username',
        ),
    ]
