# Generated by Django 5.2.4 on 2025-08-10 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_rename_username_userprofile_fullname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
